AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  validator

  Sample SAM Template for validator

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  apigatewayvalidator:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: authorizer.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::544572852342:role/service-role/api-gateway-validator-role-nrnhr1wa
